[tool.poetry]
name = "replicate"
version = "0.1.0"
description = ""
authors = ["secretshardul <aeershardul@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.4"
cog = "^0.8.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
